In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

In [2]:
location2DatasetTrain = 'D:\\dropbox\\Dropbox\\Master Course\\SEM-3\\ML\\CM_CUP_Datasets\\train'
location2SaveTrainsplit='D:\\dropbox\\Dropbox\\Master Course\\SEM-3\\ML\\CM_CUP_Datasets\\60percenttrain.txt'
location2SaveTestsplit = 'D:\\dropbox\\Dropbox\\Master Course\\SEM-3\\ML\\CM_CUP_Datasets\\60percenttest.txt'

## Loading the trainingset of CUP
#### the version we used is trimmed, removing the information banner before the data

In [3]:
df = pd.read_csv(location2DatasetTrain,delimiter=',',header=None, usecols = [1,2,3,4,5,6,7,8,9,10,11,12])

### shuffling

In [4]:
df = shuffle(df,random_state=1)

### 60% for training and 40% testing

In [5]:
sixteepercent = (int)(np.ceil(df.values.shape[0]*0.6))

In [6]:
train_features = df.values[:sixteepercent,0:10]
test_features = df.values[sixteepercent:,0:10]
train_target = df.values[:sixteepercent,10:]
test_target = df.values[sixteepercent:,10:]

## saving the train and test files
#### please uncomment the cell, if the data files are not yet present

In [7]:
#saving the train and test files
#np.savetxt(location2SaveTrainsplit,df.values[sixteepercent:,:],delimiter =',',fmt='%f')
#np.savetxt(location2SaveTestsplit,df.values[sixteepercent:,:],delimiter =',',fmt='%f')

## Training a LLS model from sikitlearn with a SVD solver

In [8]:
#from sklearn import linear_model
from sklearn.linear_model import Ridge
#reg = linear_model.LinearRegression()
reg = Ridge(alpha=1.0,solver='svd',tol=0.000001,fit_intercept=True)
import time
t1=time.time()
reg.fit (train_features, train_target)
t2=time.time()
print('time:',(t2-t1)*1000)

time: 231.05430603027344


In [9]:
reg.coef_

array([[ -4.93464519e-01,   1.66455830e+00,  -2.77512881e-01,
         -5.84060810e-01,  -1.24829627e+00,  -1.82867253e-03,
         -5.81070928e-01,   3.42878098e+00,  -1.77038814e+00,
          2.49755673e-01],
       [ -1.28996090e+00,  -1.12973130e+00,  -1.43327099e+00,
         -1.02208721e+00,   2.96086047e-01,  -1.50807657e+00,
         -1.20340543e+00,  -9.38985924e-01,   9.11270270e-01,
         -1.42108530e+00]])

## computing the norm of residuals for the test set

In [10]:
#reg.score(test_features,test_target)
#(((test_features.dot(reg.coef_.transpose())- test_target)**2).sum(axis=1)/(2 * test_target.shape[0])).mean()
np.sqrt(((test_features.dot(reg.coef_.transpose())- test_target)**2).sum(axis=0))

array([ 244.37040204,  275.40880744])

## LLS with a stochastic gradient descent method

In [11]:
reg = Ridge(alpha=0.1,max_iter=1000,solver='sag',fit_intercept=True)
import time
t1=time.time()
reg.fit (train_features, train_target)
t2=time.time()
print('time:',(t2-t1)*1000)
np.sqrt(((test_features.dot(reg.coef_.transpose())- test_target)**2).sum(axis=0))

time: 18.99242401123047


array([ 244.35415956,  275.40903645])